services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=womens_health_db
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=${EMAIL_USER:-your-email@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-your-email-app-password}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=womens_health_db
    volumes:
      - ./SQLdump_Screenshots/Hospital_Management_App_prod_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: